version: '3.8'

services:
  # Jaeger All-in-One - Configuração AWS Academy
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger-aws
    ports:
      - "16686:16686"        # Web UI
      - "14268:14268"        # Collector HTTP
      - "6831:6831/udp"      # Thrift binary
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_DISABLED=false
      - SPAN_STORAGE_TYPE=memory
      - JAEGER_AGENT_HOST=localhost
    network_mode: "host"
    restart: unless-stopped

  # HotROD - Configuração AWS Academy
  hotrod:
    image: jaegertracing/example-hotrod:1.54
    container_name: hotrod-aws
    ports:
      - "8080:8080"
    environment:
      - JAEGER_ENDPOINT=http://localhost:14268/api/traces
      - JAEGER_AGENT_HOST=localhost
      - JAEGER_AGENT_PORT=6831
    network_mode: "host"
    depends_on:
      - jaeger
    restart: unless-stopped 